# Generated by Django 4.1.1 on 2022-09-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtUser',
        ),
    ]
