version: '2.2'

services:

    db:
        image: mysql:8.0
        container_name: artMySQL
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - artnet

    web:
        build: .
        container_name: artApp
        restart: unless-stopped
        env_file: .env
        depends_on:
            - db
        volumes:
            - .:/app
        networks:
            - artnet

    nginx:
        image: nginx
        container_name: artNginx
        restart: unless-stopped
        env_file: .env
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
        volumes:
            - ./data/nginx/nginx${STATE}.conf:/etc/nginx/nginx.conf
            - ./data/nginx/conf.d:/etc/nginx/conf.d
            - .:/app
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - artnet


    certbot:
        image: certbot/certbot
        container_name: artCertbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        networks:
            - artnet

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: artPhpMyAdmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - artnet

networks:
    artnet:
        driver: bridge
