version: '2.12'

services:
    db:
        image: mysql:8.0
        container_name: artMySQL
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - app

    web:
        build: .
        container_name: artApp
        restart: unless-stopped
        env_file: .env
        depends_on:
            - db
        volumes:
            - .:/app
        networks:
            - app

    nginx:
        image: nginx:alpine
        container_name: artNginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
        volumes:
            - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/app
        networks:
            - app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: artPhpMyAdmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - app

networks:
    app:
        driver: bridge
