# Generated by Django 4.1.1 on 2022-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumb',
            field=models.BooleanField(default=False),
        ),
    ]
