# Generated by Django 4.1.1 on 2022-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
