# Generated by Django 4.1.1 on 2022-10-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
