# Generated by Django 4.1.1 on 2022-10-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_product_slug_technique_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
