# Generated by Django 4.1.1 on 2022-10-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slg',
        ),
    ]
