# Generated by Django 4.1.1 on 2022-10-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_rename_slug_product_slg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slg',
            new_name='slug',
        ),
    ]
