# Generated by Django 4.1.1 on 2022-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_alter_author_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
    ]
