# Generated by Django 4.1.1 on 2022-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0014_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Техника'),
        ),
    ]
