# Generated by Django 4.1.1 on 2022-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0016_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
    ]
