# Generated by Django 4.1.1 on 2022-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_alter_author_first_name_alter_author_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
