# Generated by Django 4.1.1 on 2022-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0018_alter_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Категория'),
        ),
    ]
