# Generated by Django 4.1.1 on 2022-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0019_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
    ]
