# Generated by Django 4.1.1 on 2022-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0020_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.CharField(max_length=200, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Техника'),
        ),
    ]
