# Generated by Django 4.1.1 on 2022-10-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0021_alter_product_materials_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
