# Generated by Django 4.1.1 on 2022-10-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0022_alter_author_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='vertical',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vertical',
        ),
    ]
