# Generated by Django 4.1.1 on 2022-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0023_remove_gallery_vertical_remove_video_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contacts_off',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
