# Generated by Django 4.1.1 on 2022-10-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0025_alter_artcomment_product_alter_artcomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='video',
            name='clip',
            field=models.FileField(blank=True, upload_to='videos/%Y/%m/%d/', verbose_name='Видео'),
        ),
    ]
