# Generated by Django 4.1.1 on 2022-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0027_config_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция'),
        ),
    ]
