# Generated by Django 4.1.1 on 2022-10-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0030_product_thumb_of_day_alter_product_th_of_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumb_of_day',
        ),
    ]
